# Generated by Django 5.0.1 on 2024-01-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_moviedata_typ"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviedata",
            name="image",
            field=models.ImageField(
                default="images/None/Noimg.jpg", upload_to="Images/"
            ),
        ),
    ]
